# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62a3fffad2d860d1c6749790710eea3a6c2745fbc374f7ea548d112ec0f90c0526bbdd5d843f50b6bab0c16b4c3758bdf3c85494de283300457192534bc36126

test:
  secret_key_base: 0b2fd7f69d66f08d562b6ddbe54ef112738e9d3f589e6db151b36048e79a3c4b558bbf0e3676c27809ef3c1726d753f67aa13d6a6b408763e05628d730526295

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
